# 由 GitHub 上 history-check 的核对结果整理（2026-10-02）：资料键 → (核对通过的网址, 核对方式)
# 核对方式：live＝直接打开网页；archive 时间＝网站拒绝程序访问，改用网页时光机当时的存档核对；pubmed＝用 PubMed 接口核对；search＝网站拒绝程序读取，用搜索引擎的原文摘要核对
CHECKED = {
 'adventist': ('https://en.wikipedia.org/wiki/Millerites', 'live'),
 'ag_hist': ('https://ag.org/About/About-the-AG/History', 'archive 20260904170718'),
 'anabapt': ('https://www.britannica.com/topic/Anabaptists', 'archive 20260907042701'),
 'anglican': ('https://www.britannica.com/topic/Anglicanism', 'archive 20260927061008'),
 'anglicancomm': ('https://www.anglicancommunion.org/structures/member-churches.aspx', 'archive 20260228040703'),
 'augsburg': ('https://bookofconcord.org/augsburg-confession/', 'live'),
 'augustine': ('https://www.britannica.com/biography/Saint-Augustine', 'archive 20260930145916'),
 'awakening': ('https://www.britannica.com/event/Great-Awakening', 'archive 20260605172402'),
 'awakening2': ('https://www.britannica.com/topic/Second-Great-Awakening', 'archive 20260729091024'),
 'baptist': ('https://www.britannica.com/biography/John-Smyth', 'archive 20260210135437'),
 'brethren': ('https://www.britannica.com/topic/Plymouth-Brethren', 'archive 20260714093925'),
 'bwa2': ('https://baptistworld.org/', 'live'),
 'calvin': ('https://www.britannica.com/biography/John-Calvin', 'archive 20260906161140'),
 'chalc_ce': ('https://www.newadvent.org/cathen/03555a.htm', 'live'),
 'chalcedon': ('https://www.britannica.com/event/Council-of-Chalcedon', 'archive 20260905193009'),
 'creed_ce': ('https://www.newadvent.org/cathen/11049a.htm', 'live'),
 'disappoint': ('https://en.wikipedia.org/wiki/Great_Disappointment', 'live'),
 'disciples': ('https://www.britannica.com/topic/Disciples-of-Christ', 'archive 20260219170456'),
 'dispens': ('https://en.wikipedia.org/wiki/Dispensationalism', 'live'),
 'east': ('https://www.newadvent.org/cathen/10755a.htm', 'live'),
 'edson_wiki': ('https://en.wikipedia.org/wiki/Hiram_Edson', 'live'),
 'egw_est': ('https://whiteestate.org/about/egwbio/', 'live'),
 'egw_wiki': ('https://en.wikipedia.org/wiki/Ellen_G._White', 'live'),
 'ephesus': ('https://www.newadvent.org/cathen/05491a.htm', 'live'),
 'ephesus_ce': ('https://www.newadvent.org/cathen/05491a.htm', 'live'),
 'ethiopia': ('https://en.wikipedia.org/wiki/Ethiopian_Orthodox_Tewahedo_Church', 'live'),
 'fraser': ('https://pubmed.ncbi.nlm.nih.gov/11434797/', 'pubmed'),
 'gc1863': ('https://adventistreview.org/magazine-article/a-pivotal-session/', 'search'),
 'gregory': ('https://www.britannica.com/biography/Saint-Gregory-I', 'archive 20160804024316'),
 'gutenberg': ('https://www.britannica.com/biography/Johannes-Gutenberg', 'archive 20260921031836'),
 'hus': ('https://www.britannica.com/biography/Jan-Hus', 'archive 20260908082914'),
 'ignatius': ('https://www.newadvent.org/fathers/0105.htm', 'live'),
 'justin': ('https://www.newadvent.org/fathers/0126.htm', 'live'),
 'laodicea': ('https://www.newadvent.org/fathers/3806.htm', 'live'),
 'larue': ('https://www.adventist.asia/news/how-did-one-mans-journey-start-a-global-movement-1/', 'archive 20240815041948'),
 'lbc1689': ('https://www.the1689confession.com/', 'live'),
 'luther': ('https://www.britannica.com/biography/Martin-Luther', 'archive 20260927061152'),
 'luther_bible': ('https://en.wikipedia.org/wiki/Luther_Bible', 'live'),
 'luther_ce': ('https://www.newadvent.org/cathen/09438b.htm', 'live'),
 'luther_jews': ('https://en.wikipedia.org/wiki/Martin_Luther_and_antisemitism', 'live'),
 'luther_name': ('https://en.wikipedia.org/wiki/History_of_Lutheranism', 'live'),
 'luther_pref': ('https://christianhistoryinstitute.org/magazine/article/luthers-breakthrough', 'live'),
 'luther_worms': ('https://christianhistoryinstitute.org/magazine/article/diet-of-worms', 'live'),
 'lutheranism': ('https://en.wikipedia.org/wiki/Lutheranism', 'live'),
 'lwf': ('https://lutheranworld.org/who-we-are', 'live'),
 'menno': ('https://www.britannica.com/biography/Menno-Simons', 'archive 20260909183348'),
 'menno_wiki': ('https://en.wikipedia.org/wiki/Menno_Simons', 'live'),
 'methodism': ('https://www.britannica.com/topic/Methodism', 'archive 20260919094935'),
 'milan': ('https://www.britannica.com/topic/Edict-of-Milan', 'archive 20260914085548'),
 'miller': ('https://www.britannica.com/biography/William-Miller', 'archive 20260224035840'),
 'morrison': ('https://www.britannica.com/biography/Robert-Morrison', 'archive 20250913134533'),
 'nee': ('https://www.britannica.com/biography/Watchman-Nee', 'archive 20260704063253'),
 'nee_wiki': ('https://en.wikipedia.org/wiki/Watchman_Nee', 'live'),
 'nicaea': ('https://www.britannica.com/event/First-Council-of-Nicaea-325', 'archive 20260904104645'),
 'nicaea_ce': ('https://www.newadvent.org/cathen/11044a.htm', 'live'),
 'oriental': ('https://www.britannica.com/topic/Oriental-Orthodox-church', 'archive 20251111085744'),
 'pentecost': ('https://www.britannica.com/topic/Pentecostalism', 'archive 20260911043920'),
 'pentecost_wiki': ('https://en.wikipedia.org/wiki/Pentecostalism', 'live'),
 'pew': ('https://www.pewresearch.org/religion/2011/12/19/global-christianity-exec/', 'live'),
 'pliny': ('https://www.britannica.com/biography/Pliny-the-Younger', 'archive 20260831132437'),
 'pliny_txt': ('https://sourcebooks.fordham.edu/source/pliny1.asp', 'live'),
 'presby': ('https://www.britannica.com/biography/John-Knox', 'archive 20260220211248'),
 'quaker': ('https://www.britannica.com/topic/Friends', 'archive 20260427012503'),
 'restoration': ('https://en.wikipedia.org/wiki/Restoration_Movement', 'live'),
 'ricci': ('https://www.britannica.com/biography/Matteo-Ricci', 'archive 20260920050025'),
 'schism': ('https://www.britannica.com/event/Schism-of-1054', 'archive 20190401032957'),
 'scot_ref': ('https://en.wikipedia.org/wiki/Scottish_Reformation', 'live'),
 'sda_beliefs': ('https://www.adventist.org/beliefs/', 'archive 20260418102002'),
 'sda_brit': ('https://www.britannica.com/topic/Seventh-day-Adventist-church', 'archive 20251225170630'),
 'sda_china': ('https://en.wikipedia.org/wiki/Seventh-day_Adventist_Church_in_China', 'live'),
 'sda_dead': ('https://www.adventist.org/death-and-resurrection/', 'archive 20250613201700'),
 'sda_egw': ('https://www.adventist.org/gift-of-prophecy/', 'archive 20250501091554'),
 'sda_hist': ('https://www.adventist.org/who-are-seventh-day-adventists/history-of-seventh-day-adventists/', 'archive 20250613192659'),
 'sda_hist_wiki': ('https://en.wikipedia.org/wiki/History_of_the_Seventh-day_Adventist_Church', 'live'),
 'sda_sabbath': ('https://www.adventist.org/the-sabbath/', 'archive 20250609151646'),
 'sda_sanct': ('https://www.adventist.org/christs-ministry-in-the-heavenly-sanctuary/', 'archive 20250613193423'),
 'sda_stats': ('https://www.adventist.org/statistics/', 'archive 20250512212121'),
 'sda_supper': ('https://www.adventist.org/the-lords-supper/', 'archive 20250428093407'),
 'sda_trinity': ('https://www.adventist.org/trinity/', 'archive 20250621072731'),
 'sda_wiki': ('https://en.wikipedia.org/wiki/Seventh-day_Adventist_Church', 'live'),
 'sdb2': ('https://www.sabbathrecorder.com/2013/10/22/a-thumbnail-sketch-of-seventh-day-baptists/', 'live'),
 'sdb_org': ('https://seventhdaybaptist.org/', 'live'),
 'socrates': ('https://www.newadvent.org/fathers/26015.htm', 'live'),
 'sozomen': ('https://www.newadvent.org/fathers/26027.htm', 'live'),
 'stele': ('https://en.wikipedia.org/wiki/Xi%27an_Stele', 'live'),
 'sunday321': ('https://www.britannica.com/topic/Sunday-day-of-week', 'archive 20260826091336'),
 'supremacy': ('https://en.wikipedia.org/wiki/Acts_of_Supremacy', 'live'),
 'taylor': ('https://en.wikipedia.org/wiki/Hudson_Taylor', 'live'),
 'tertullian': ('https://www.britannica.com/biography/Tertullian', 'archive 20260908154128'),
 'theodosius': ('https://www.britannica.com/biography/Theodosius-I', 'archive 20260806185347'),
 'theses': ('https://www.britannica.com/event/Ninety-five-Theses', 'archive 20260927202118'),
 'theses_txt': ('https://www.luther.de/en/95thesen.html', 'live'),
 'thessalonica': ('https://en.wikipedia.org/wiki/Edict_of_Thessalonica', 'live'),
 'tjc': ('https://tjc.org/', 'live'),
 'tjc_wiki': ('https://en.wikipedia.org/wiki/True_Jesus_Church', 'live'),
 'trent': ('https://www.britannica.com/event/Council-of-Trent', 'archive 20260726195518'),
 'trinity_ce': ('https://www.newadvent.org/cathen/15047a.htm', 'live'),
 'vatican2': ('https://www.britannica.com/event/Second-Vatican-Council', 'archive 20260920092952'),
 'vatican2_wiki': ('https://en.wikipedia.org/wiki/Second_Vatican_Council', 'live'),
 'wald_ce': ('https://www.newadvent.org/cathen/15527b.htm', 'live'),
 'waldenses': ('https://www.britannica.com/topic/Waldenses', 'archive 20260912082459'),
 'wcrc': ('https://wcrc.ch/about-us', 'archive 20240803020209'),
 'wcrc2': ('https://wcrc.eu/', 'live'),
 'wesley': ('https://www.britannica.com/biography/John-Wesley', 'archive 20260902231556'),
 'westminster': ('https://www.britannica.com/topic/Westminster-Confession', 'archive 20260219152218'),
 'williams': ('https://en.wikipedia.org/wiki/First_Baptist_Church_in_America', 'live'),
 'wmc': ('https://worldmethodistcouncil.org/about/', 'live'),
 'worms_wiki': ('https://en.wikipedia.org/wiki/Diet_of_Worms', 'live'),
 'wyc_ce': ('https://www.newadvent.org/cathen/15722a.htm', 'live'),
 'wycliffe': ('https://www.britannica.com/biography/John-Wycliffe', 'archive 20260928021659'),
 'zwingli': ('https://www.britannica.com/biography/Huldrych-Zwingli', 'archive 20260713232550'),
 # 2026-10-04：《教义问答》一章的资料（GitHub 上直接下载原文核对）
 'valentine': ('https://encyclopedia.adventist.org/assets/pdf/article-6JJ3.pdf', 'live'),
 'unruh77': ('https://www.adventistlaymen.org/Selected%20Documents%20and%20Manuscripts/THE%20SEVENTH-DAY%20ADVENTIST%20EVANGELICAL%20CONFERENCES%20OF%201955-1956.pdf', 'live'),
 'br1914': ('https://documents.adventistarchives.org/Books/BR1914.pdf', 'live'),
 'br1949': ('https://documents.adventistarchives.org/Books/BR1949.pdf', 'live'),
 'min1956': ('https://cdn.ministerialassociation.org/cdn/ministrymagazine.org/issues/1956/issues/MIN1956-09.pdf', 'live'),
 'knight03': ('https://digitalcommons.andrews.edu/adventist-books/1', 'live'),
 'whidden03': ('https://www.ministrymagazine.org/archive/2003/08/questions-on-doctrine-then-and-now.html', 'live'),
 'douglass04': ('https://www.ministrymagazine.org/archive/2004/08/thoughts-on-the-republished-questions-on-doctrine.html', 'live'),
 'rh1896': ('https://documents.adventistarchives.org/Periodicals/RH/RH18961215-V73-50.pdf', 'live'),
 'yi1900': ('https://documents.adventistarchives.org/Periodicals/YI/YI19001220-V48-50.pdf', 'live'),
 'qod2007': ('https://digitalcommons.andrews.edu/qod/', 'live'),
 'w_andreasen': ('https://en.wikipedia.org/wiki/M._L._Andreasen', 'live'),
 # 2026-10-04：补充问答页的资料（GitHub 上直接打开原文核对）
 'da123': ('https://ccel.org/ccel/white/desire.xv.html', 'live'),
 'da671': ('https://ccel.org/ccel/white/desire.lxxvi.html', 'live'),
 'da686': ('https://ccel.org/ccel/white/desire.lxxvii.html', 'live'),
 'da688': ('https://ccel.org/ccel/white/desire.lxxvii.html', 'live'),
 'da692': ('https://ccel.org/ccel/white/desire.lxxvii.html', 'live'),
 'da693': ('https://ccel.org/ccel/white/desire.lxxvii.html', 'live'),
 'rh1887': ('https://documents.adventistarchives.org/Periodicals/RH/RH18871108-V64-44.pdf', 'live'),
 'rh1888': ('https://documents.adventistarchives.org/Periodicals/RH/RH18880327-V65-13.pdf', 'live'),
 'st1888': ('https://documents.adventistarchives.org/Periodicals/ST/ST18880323-V14-12.pdf', 'live'),
 'sc17': ('https://ccel.org/ccel/white/steps.v.html', 'live'),
 'irving': ('https://www.encyclopedia.com/people/philosophy-and-religion/protestant-christianity-biographies/edward-irving', 'live'),
 'tgc': ('https://www.thegospelcoalition.org/article/you-asked-did-jesus-assume-a-fallen-human-nature/', 'live'),
}
